name: Qdapp

on:
  schedule:
    - cron: '*/10 * * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./Qrd/requirements.txt 
        
      - name: '公众号iosrule' 
        run: python3 ./Qdapp/Qdapp.py 
        env:
            DJJ_BARK_COOKIE: ${{ secrets.DJJ_BARK_COOKIE }}
            DJJ_SEVER_JIANG: ${{ secrets.DJJ_SEVER_JIANG }}
            readapp_url: ${{ secrets.readapp_url }}
            readapp_hd: ${{ secrets.readapp_hd }}
            readapp_bt: ${{ secrets.readapp_bt }}
